/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as GridRouteImport } from './routes/grid'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HabitTaskIdRouteImport } from './routes/habit.$taskId'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const GridRoute = GridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitTaskIdRoute = HabitTaskIdRouteImport.update({
  id: '/habit/$taskId',
  path: '/habit/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/grid': typeof GridRoute
  '/journal': typeof JournalRoute
  '/manage': typeof ManageRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/habit/$taskId': typeof HabitTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/grid': typeof GridRoute
  '/journal': typeof JournalRoute
  '/manage': typeof ManageRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/habit/$taskId': typeof HabitTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/grid': typeof GridRoute
  '/journal': typeof JournalRoute
  '/manage': typeof ManageRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/habit/$taskId': typeof HabitTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/grid'
    | '/journal'
    | '/manage'
    | '/settings'
    | '/stats'
    | '/habit/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/grid'
    | '/journal'
    | '/manage'
    | '/settings'
    | '/stats'
    | '/habit/$taskId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/grid'
    | '/journal'
    | '/manage'
    | '/settings'
    | '/stats'
    | '/habit/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  GridRoute: typeof GridRoute
  JournalRoute: typeof JournalRoute
  ManageRoute: typeof ManageRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  HabitTaskIdRoute: typeof HabitTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid': {
      id: '/grid'
      path: '/grid'
      fullPath: '/grid'
      preLoaderRoute: typeof GridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habit/$taskId': {
      id: '/habit/$taskId'
      path: '/habit/$taskId'
      fullPath: '/habit/$taskId'
      preLoaderRoute: typeof HabitTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  GridRoute: GridRoute,
  JournalRoute: JournalRoute,
  ManageRoute: ManageRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  HabitTaskIdRoute: HabitTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
